// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJMScQtzKX0f-AEcn6VrGfA7DYBissYw',
    appId: '1:418940085189:web:1b6875706360b1e2f161ac',
    messagingSenderId: '418940085189',
    projectId: 'vehicleminiproject',
    authDomain: 'vehicleminiproject.firebaseapp.com',
    storageBucket: 'vehicleminiproject.appspot.com',
    measurementId: 'G-BCMLNTE2RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6glVLEb7AuMsRQ_Zuv9k-ILbckZB80VU',
    appId: '1:418940085189:android:348c8b6427012cb4f161ac',
    messagingSenderId: '418940085189',
    projectId: 'vehicleminiproject',
    storageBucket: 'vehicleminiproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0vRBU2QPFNOgi6GQ8eM5UMGa8EhQDyrc',
    appId: '1:418940085189:ios:1c4c3a20eb9b3fe2f161ac',
    messagingSenderId: '418940085189',
    projectId: 'vehicleminiproject',
    storageBucket: 'vehicleminiproject.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0vRBU2QPFNOgi6GQ8eM5UMGa8EhQDyrc',
    appId: '1:418940085189:ios:1c4c3a20eb9b3fe2f161ac',
    messagingSenderId: '418940085189',
    projectId: 'vehicleminiproject',
    storageBucket: 'vehicleminiproject.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJMScQtzKX0f-AEcn6VrGfA7DYBissYw',
    appId: '1:418940085189:web:bc5829332cf2b346f161ac',
    messagingSenderId: '418940085189',
    projectId: 'vehicleminiproject',
    authDomain: 'vehicleminiproject.firebaseapp.com',
    storageBucket: 'vehicleminiproject.appspot.com',
    measurementId: 'G-QX8632XPSB',
  );
}
